server:
  port: 8084
spring:
  application:
    name: rating-service
  datasource:
    url: jdbc:mysql:localhost:3306/feedbackdb
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/  
