spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/user/*
          filters:
            - JwtAuthFilter
        - id: Meeting-Service
          uri: lb://Meeting-Service
          predicates:
            - Path=/meeting/**
          filters:
            - JwtAuthFilter
        - id: Auth-Service
          uri: lb://Auth-Service
          predicates:
            - Path=/auth/**
        - id: Rating-Service
          uri: lb://Rating-Service
          predicates:
            - Path=/rating/**
          filters:
            - JwtAuthFilter
    
server:
  port: 8080
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
    - name: User-Service
      url: /user/v3/api-docs
    - name: Auth-Service
      url: /auth/v3/api-docs
    - name: Rating-Service
      url: /rating/v3/api-docs
    - name: Meeting-Service
      url: /meeting/v3/api-docs


