spring:
  application:
    name: Auth-Service
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/vLearn_auth?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.5

server:
  port: 8081
  servlet:
    context-path: /auth
    

  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/